const mongoose = require('mongoose');

const schoolSchema = new mongoose.Schema({
    schoolId: {
        type: String,
        unique: true,
        sparse: true,  // Allow null during creation, will be generated by pre-save
        index: true
    },
    name: {
        type: String,
        required: [true, 'School name is required'],
        trim: true,
        maxlength: [200, 'School name cannot exceed 200 characters']
    },
    code: {
        type: String,
        unique: true,
        sparse: true,  // Allow null during creation, will be generated by pre-save
        index: true
        // Format: First letter + Last letter + number (e.g., SL1, SM2)
    },
    address: {
        type: String,
        trim: true,
        default: ''
    },
    phone: {
        type: String,
        trim: true,
        default: ''
    },
    email: {
        type: String,
        trim: true,
        lowercase: true,
        default: ''
    },
    principalName: {
        type: String,
        trim: true,
        default: ''
    },
    studentCount: {
        type: Number,
        default: 0
    },
    isActive: {
        type: Boolean,
        default: true,
        index: true
    },
    createdAt: {
        type: Date,
        default: Date.now
    },
    updatedAt: {
        type: Date,
        default: Date.now
    }
}, {
    timestamps: true
});

// Generate school code from name (First letter + Last letter + number)
schoolSchema.statics.generateSchoolCode = async function (schoolName) {
    const words = schoolName.trim().split(/\s+/);

    // Get first letter of first word
    const firstLetter = words[0].charAt(0).toUpperCase();

    // Get first letter of last word
    const lastLetter = words[words.length - 1].charAt(0).toUpperCase();

    // Base code
    const baseCode = firstLetter + lastLetter;

    // Find the next available number for this code
    const existingSchools = await this.find({
        code: new RegExp(`^${baseCode}\\d+$`)
    }).sort({ code: -1 }).limit(1);

    let number = 1;
    if (existingSchools.length > 0) {
        const lastCode = existingSchools[0].code;
        const lastNumber = parseInt(lastCode.replace(baseCode, ''));
        number = lastNumber + 1;
    }

    return baseCode + number;
};

// Auto-generate school code and ID before saving
schoolSchema.pre('save', async function (next) {
    // Only for new documents
    if (!this.isNew) {
        this.updatedAt = Date.now();
        return next();
    }

    try {
        // Generate school code if not provided
        if (!this.code) {
            this.code = await this.constructor.generateSchoolCode(this.name);
        }

        // Generate school ID if not provided (sequential)
        if (!this.schoolId) {
            const lastSchool = await this.constructor.findOne({})
                .sort({ createdAt: -1 })
                .lean();

            let nextId = 1;
            if (lastSchool && lastSchool.schoolId) {
                const currentId = parseInt(lastSchool.schoolId);
                if (!isNaN(currentId)) {
                    nextId = currentId + 1;
                }
            }

            this.schoolId = String(nextId).padStart(2, '0');
        }

        next();
    } catch (error) {
        console.error('Error in pre-save hook:', error);
        next(error);
    }
});

module.exports = mongoose.model('School', schoolSchema);
